import "./globals.css";

export const metadata = {
  title: "first task",
  description: "Generated by Tamzid Ull Monir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
        {children}
      </body>
    </html>
  );
}
